version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: honeybadger
    versions:
    - 4.7.3
  - dependency-name: bundler
    versions:
    - 2.2.10
    - 2.2.11
    - 2.2.12
    - 2.2.13
    - 2.2.14
    - 2.2.7
    - 2.2.8
    - 2.2.9
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.2
  - dependency-name: simplecov
    versions:
    - 0.21.2
  - dependency-name: rake
    versions:
    - 13.0.3
  rebase-strategy: disabled
