name: Run specs

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec
      - name: Run rubocop
        run: |
          bundle exec rubocop
